---
- name: Update caches
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"

- name: upgrade a server
  apt: upgrade=full
  sudo: true

- name: Install ansible required apt packages
  apt:
    pkg: "python-apt"
    state: present
