---
galaxy_info:
  author: Pierre Paul Lefebvre, Rafe Colton
  description: Installs and configure haproxy
  company: Pheromone, ModCloth
  license: Apache v2
  min_ansible_version: 1.5
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: SmartOS
  - name: CentOS
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - networking
  - system
  - web
dependencies: []
